name: comment-errors
on:
  workflow_run:
    workflows:
      - continuous-delivery-action
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1